<?php

return [
    "IsContract" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\IsContract",
    "ContractAttachment" => "gisgkh\\types\\Base\\AttachmentType",
    "IsNotContract" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\IsNotContract",
    "ComptetionDate" => "string",
    "Period" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\Period",
    "Start" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\Period\\Start",
    "End" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\Period\\End",
    "ContractBase" => "gisgkh\\types\\NsiBase\\nsiRef",
    "Offer" => "string",
    "ApartmentBuildingOwner" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ApartmentBuildingOwner",
    "RegOrg" => "gisgkh\\types\\HouseManagement\\DRSORegOrgType",
    "Ind" => "gisgkh\\types\\HouseManagement\\DRSOIndType",
    "LivingHouseOwner" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\LivingHouseOwner",
    "Organization" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\Organization",
    "IsPlannedVolume" => "string",
    "ContractSubject" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ContractSubject",
    "ServiceType" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ContractSubject\\ServiceType",
    "MunicipalResource" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ContractSubject\\MunicipalResource",
    "PlannedVolume" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ContractSubject\\PlannedVolume",
    "CountingResource" => "string",
    "SpecifyingQualityIndicators" => "string",
    "ObjectAddress" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ObjectAddress",
    "Pair" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ObjectAddress\\Pair",
    "HeatingSystemType" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ObjectAddress\\Pair\\HeatingSystemType",
    "Quality" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\Quality",
    "QualityIndicator" => "gisgkh\\types\\NsiBase\\nsiRef",
    "IndicatorValue" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\Quality\\IndicatorValue",
    "OtherQualityIndicator" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\OtherQualityIndicator",
    "TemperatureChart" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\TemperatureChart",
    "BillingDate" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\BillingDate",
    "PaymentDate" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\PaymentDate",
    "ProvidingInformationDate" => "gisgkh\\types\\HouseManagement\\ExportSupplyResourceContractType\\ProvidingInformationDate"
];
