<?php

return [
    "IsContract" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\IsContract",
    "ContractAttachment" => "gisgkh\\types\\Base\\AttachmentType",
    "IsNotContract" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\IsNotContract",
    "ComptetionDate" => "string",
    "Period" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\Period",
    "Start" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\Period\\Start",
    "End" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\Period\\End",
    "ContractBase" => "gisgkh\\types\\NsiBase\\nsiRef",
    "Offer" => "string",
    "ApartmentBuildingOwner" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\ApartmentBuildingOwner",
    "RegOrg" => "gisgkh\\types\\HouseManagement\\DRSORegOrgType",
    "Ind" => "gisgkh\\types\\HouseManagement\\DRSOIndType",
    "LivingHouseOwner" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\LivingHouseOwner",
    "Organization" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\Organization",
    "IsPlannedVolume" => "string",
    "ContractSubject" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\``",
    "CountingResource" => "string",
    "SpecifyingQualityIndicators" => "string",
    "ObjectAddress" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\ObjectAddress",
    "Pair" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\ObjectAddress\\Pair",
    "HeatingSystemType" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\ObjectAddress\\Pair\\HeatingSystemType",
    "Quality" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\Quality",
    "QualityIndicator" => "gisgkh\\types\\NsiBase\\nsiRef",
    "IndicatorValue" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\Quality\\IndicatorValue",
    "OtherQualityIndicator" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\OtherQualityIndicator",
    "TemperatureChart" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\TemperatureChart",
    "BillingDate" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\BillingDate",
    "PaymentDate" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\PaymentDate",
    "ProvidingInformationDate" => "gisgkh\\types\\HouseManagement\\SupplyResourceContractType\\ProvidingInformationDate"
];
